services:
  web:
    image: web
    build:
      context: .
      dockerfile: src/Web/Dockerfile


  db:
    image: postgres:alpine
    container_name: db
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: db
    ports:
      - "5432:5432"